<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="109832" started-at="2018-04-10T04:30:03Z" finished-at="2018-04-10T04:31:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="109832" started-at="2018-04-10T04:30:03Z" finished-at="2018-04-10T04:31:53Z">
      <class name="com.powerhouse.powerMailAndLytics.AutoLogin">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="beforeClass" is-config="true" duration-ms="59616" started-at="2018-04-10T10:00:03Z" finished-at="2018-04-10T10:01:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="powerLytic()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="powerLytic" duration-ms="36087" started-at="2018-04-10T10:01:03Z" finished-at="2018-04-10T10:01:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powerLytic -->
        <test-method status="PASS" signature="aftermethod(org.testng.ITestResult)[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="aftermethod" is-config="true" duration-ms="1" started-at="2018-04-10T10:01:39Z" finished-at="2018-04-10T10:01:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=powerLytic status=SUCCESS method=AutoLogin.powerLytic()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="FAIL" signature="powerMail()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="powerMail" duration-ms="9878" started-at="2018-04-10T10:01:39Z" finished-at="2018-04-10T10:01:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.powerhouse.powerMailAndLytics.AutoLogin.powerMail(AutoLogin.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powerMail -->
        <test-method status="PASS" signature="aftermethod(org.testng.ITestResult)[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="aftermethod" is-config="true" duration-ms="450" started-at="2018-04-10T10:01:49Z" finished-at="2018-04-10T10:01:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=powerMail status=FAILURE method=AutoLogin.powerMail()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.powerhouse.powerMailAndLytics.AutoLogin@47c62251]" name="afterClass" is-config="true" duration-ms="3630" started-at="2018-04-10T10:01:49Z" finished-at="2018-04-10T10:01:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.powerhouse.powerMailAndLytics.AutoLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
